### ISSUE TITLE
feat/marker_sidebar 마커 클릭시 사이드바 열리는 기능

### ISSUE THREAD

**Issue by mhsong95** [boostcampwm-2021/Web11-Donggle#51]
### 🔨 기능 설명
마커 클릭시 사이드바가 열리는 기능

### 📑 구현할 내용
- [x] 마커(DOM 엘리먼트) 클릭시 우측 사이드바 열리는 이벤트 구현
- [x] 사이드바에 주소, 별점 등 정보를 전달하도록 구현

### 🚧 주의 사항
- 컴포넌트 라이프사이클에서 벗어나있는 DOM 엘리먼트로부터 React 컴포넌트인 사이드바를 렌더링

**Comment by isanghaessi** [comment]
- [x] 마커 마우스 인터랙션 무시
마커 dom에 드래그 안되는 속성 넣으면 좋을것 같아요!
``` css
user-select: none;
pointer-events: none;
```

**Comment by mhsong95** [comment]
```
pointer-events: none;
```
옵션을 넣으면 호버, 클릭이 안되더라구요. `user-select: none;`만 추가했습니다. 감사합니다. 

> * [x]  마커 마우스 인터랙션 무시
>   마커 dom에 드래그 안되는 속성 넣으면 좋을것 같아요!
> 
> ```css
> user-select: none;
> pointer-events: none;
> ```
